messenger/main/routes.py
import json
from flask import render_template, Blueprint, redirect, flash, url_for
from flask_login import login_user, login_required, current_user, logout_user
from messenger import db
from messenger.main.forms import LoginForm, CreateUser, CreateMessage, ReplyMessage
from messenger.models import People, MessagesSent, MessagesRecive, MessagesSentDisplay

main = Blueprint('main', __name__)


@main.route('/', methods=["GET", "POST"])
@main.route('/home', methods=["GET", "POST"])
def home():
    form = LoginForm()
    if form.validate_on_submit():
        user = db.session.query(People).filter_by(email=form.email.data).first()
        if(user and user.password == form.password.data):
            login_user(user)
            return redirect(url_for('main.messanger'))
        else:
            flash('Inccorect email or password try again')
    return render_template('home.html', form = form)


@main.route('/register', methods=["GET","POST"])
def register_account():
    form = CreateUser()
    if form.validate_on_submit():
        user = People(first_name=form.first_name.data, last_name=form.last_name.data, email=form.email.data, password=form.password.data, message_created=[], message_recived=[], message_send_display=[])
        db.session.add(user)
        db.session.commit()
        flash(f"Created Account")
        return redirect(url_for('main.home'))
    return render_template('register.html', form = form)


@main.route('/messenger', methods=["GET","POST"])
@login_required
def messanger():
    send_messages_display = db.session.query(MessagesSentDisplay).filter_by(author_email = current_user.email).all()
    recived_messages = db.session.query(MessagesRecive).filter_by(reciver_email = current_user.email).all()
    email_recived = []
    for i in range(len(recived_messages)):
        email_to_reply = db.session.query(MessagesSent).filter_by(content = recived_messages[i].content).first()
        email_recived.append(email_to_reply.author_email)
    email_recived_set = set(email_recived)
    email_recived_dict = {}
    for adress in email_recived_set:
        emails = db.session.query(MessagesSent).filter_by(author_email = adress).all()
        email_recived_dict[adress] = emails
    return render_template('messanger.html', send_messages = send_messages_display, recived_messages = email_recived_dict, user = current_user)


@main.route('/messenger/logout', methods=["GET","POST"])
@login_required
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@main.route('/messenger/new_message', methods=["GET", "POST"])
@login_required
def create_new_message():
    form = CreateMessage()
    if form.validate_on_submit():
        reciver = db.session.query(People).filter_by(email=form.reciver_email.data).first()
        if(reciver):
            new_message_sent = MessagesSent(content = form.content.data, author_email = current_user.email)
            new_message_sent_display = MessagesSentDisplay(content = form.content.data, author_email= current_user.email, reciver_email=reciver.email)
            new_message_recived = MessagesRecive(content = form.content.data, reciver_email = reciver.email)
            db.session.add_all([new_message_sent, new_message_sent_display, new_message_recived])
            db.session.commit()
            return redirect(url_for('main.messanger'))
        else:
            flash('There is no user with that email')
    return render_template('create_message.html', form = form)


@main.route('/messenger/reply_<int:msg_recived_id>', methods=["GET","POST"])
@login_required
def reply(msg_recived_id):
    form = ReplyMessage()
    msg_recived = db.session.query(MessagesRecive).filter_by(id = msg_recived_id).first()
    msg_sended = db.session.query(MessagesSent).filter_by(content=msg_recived.content).first()
    reciver = db.session.query(People).filter_by(email=msg_sended.author_email).first()
    if form.validate_on_submit():
        new_message_sent = MessagesSent(content = form.content.data, author_email = current_user.email)
        new_message_sent_display = MessagesSentDisplay(content = form.content.data, author_email= current_user.email, reciver_email=reciver.email)
        new_message_recived = MessagesRecive(content = form.content.data, reciver_email = reciver.email)
        db.session.add_all([new_message_sent, new_message_sent_display, new_message_recived])
        db.session.commit()
        return redirect(url_for('main.messanger'))
    return render_template('reply.html', form=form)


@main.route('/messenger/delete_recive_<int:msg_recived_id>', methods=["GET", "POST"])
@login_required
def delete_recived(msg_recived_id):
    msg_deleted = db.session.query(MessagesRecive).filter_by(id=msg_recived_id).first()
    db.session.delete(msg_deleted)
    db.session.commit()
    return redirect(url_for('main.messanger'))


@main.route('/messenger/delete_send_<int:msg_send_id>', methods=["GET", "POST"])
@login_required
def delete_send(msg_send_id):
    msg_send_display_deleted = db.session.query(MessagesSentDisplay).filter_by(id=msg_send_id, author_email=current_user.email).first()
    db.session.delete(msg_send_display_deleted)
    db.session.commit()
    return redirect(url_for('main.messanger'))

messenger/templates/create_message.html
{% extends "layout.html" %}
{% block content %}
<form method="POST" action="">
    {{ form.hidden_tag() }}
    <fieldset>
      <div>
        {{ form.content.label }} 
        {% if form.content.errors %}
          {{form.content}}
          <div>
          {% for erorr in form.content.errors %}
            <span>{{erorr}}</span>
          {% endfor %}
          </div>
        {% else %}
          {{form.content }}
        {% endif %}
      </div>
      <div>
        {{ form.reciver_email.label }} 
        {% if form.reciver_email.errors %}
          {{form.reciver_email}}
          <div>
          {% for erorr in form.reciver_email.errors %}
            <span>{{erorr}}</span>
          {% endfor %}
          </div>
        {% else %}
          {{form.reciver_email }}
        {% endif %}
      </div>
    </fieldset>
    <div>{{ form.submit }}</div>
  </form>
  <a href="{{url_for('main.messanger')}}">Get back to Messanger</a>
{% endblock content %}

messenger/templates/home.html
{% extends "layout.html" %}
{% block content %}
<form method="POST" action="">
    {{ form.hidden_tag() }}
    <fieldset class="no-border">
      <div>
        {{ form.email.label }} 
        {% if form.email.errors %}
          {{form.email}}
          <div>
          {% for erorr in form.email.errors %}
            <span>{{erorr}}</span>
          {% endfor %}
          </div>
        {% else %}
          {{form.email }}
        {% endif %}
      </div>
      <div>
        {{ form.password.label }}
        {% if form.password.errors %}
          {{form.password}}
          <div>
          {% for erorr in form.password.errors %}
            <span>{{erorr}}</span>
          {% endfor %}
          </div>
        {% else %}
          {{form.password }} 
        {% endif %}
      </div>
    </fieldset>
    <div>{{ form.submit }}</div>
  </form>
  <a href="{{ url_for('main.register_account')}}">Create User</a>
{% endblock content %}

messenger/templates/layout.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta
      http-equiv="X-UA-Compatible"
      content="IE=edge"
    />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1.0"
    />
    <link
      rel="stylesheet"
      href="../static/style.css"
    />
    <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200"
    />
    <link
      rel="preconnect"
      href="https://fonts.googleapis.com"
    />
    <link
      rel="preconnect"
      href="https://fonts.gstatic.com"
      crossorigin
    />
    <link
      href="https://fonts.googleapis.com/css2?family=Raleway:ital,wght@0,400;1,800&display=swap"
      rel="stylesheet"
    />
      <title>Messanger</title>
    </head>
  <body>
    {% with messages = get_flashed_messages(with_categories = True) %}
      {% if messages %}
        {% for category, message in messages %}
          <div class="alarm">
          {{message}}
          </div>
        {% endfor %}
      {% endif %}
    {% endwith %}
    {% block content %}
    {% endblock content %}
  </body>
</html>

messenger/templates/messanger.html
{% extends "layout.html" %}
{% block content %}
    <div class="messenger-app">
        <span class="welcome">
            Welcome {{user.first_name}} {{user.last_name}}
        </span><br>
        <span class="welcome">{{user.email}}</span>
        <div class="container-message">
            <span class="sent-text">
                Sent messages:
            </span>
            <div>
                <ol>
                {% if send_messages %}
                    {% for msg in send_messages %}
                    <li>
                        <div class="msg-container">
                            <div class="title-content mg-bt-1">
                                <span class="bold">Send to:</span>
                                <span> {{msg.reciver_email}}</span>
                            </div>
                            <div class="title-content mg-bt-1">
                                <span class="bold">Content: </span>
                                <textarea disabled> {{ msg.content }}</textarea>
                            </div>
                            <a class = "message-delete-right" href="{{url_for('main.delete_send', msg_send_id = msg.id)}}">Delete</a>
                        </div>        
                    </li><br>
                    {% endfor %}
                    <br>
                {% endif %}
                </ol>
                <a class = "messenger-ref" href="{{url_for('main.create_new_message')}}">Create new message</a>
            </div>
        </div>
        <div class="container-message">
            <span class="recived-text">
                Recived messages:
            </span>
            <div>
                <ol>
                {% for key, value in recived_messages.items() %}
                    {% if value.__class__.__name__ == 'list' %}
                        {% for msg in value %}
                            <li>
                                <div class="msg-container">
                                    <div class="title-content">
                                        <span class="bold">Recived from</span>
                                        <span> {{ key }}:</span>
                                    </div>
                                    <div class="title-content">
                                        <span class="bold">Content:</span>
                                        <textarea disabled> {{ msg.content }}</textarea>
                                    </div>
                            </li>
                            <div class="title-content align-gap">
                                <a class = "message-replay" href="{{url_for('main.reply', msg_recived_id = msg.id)}}">Replay</a>
                                <a class = "message-delete-left" href="{{url_for('main.delete_recived', msg_recived_id = msg.id)}}">Delete</a>
                            </div>
                        {% endfor %}
                    {% else %}
                        <li>
                            <div class="msg-container">
                                <div class="title-content">
                                    <span class="bold">Recived from</span>
                                    <span> {{ key }}:</span>
                                </div>
                                <div class="title-content">
                                    <span class="bold">Content:</span>
                                    <textarea disabled> {{ value.content }}</textarea>
                                </div>
                        </li>
                        <div class="title-content align-gap">
                            <a class = "message-replay" href="{{url_for('main.reply', msg_recived_id = value.id)}}">Replay</a>
                            <a class = "message-delete-left" href="{{url_for('main.delete_recived', msg_recived_id = value.id)}}">Delete</a>
                        </div>
                    {% endif %}
                {% endfor %}
                </ol>
            </div>
        </div>
        <a class = "messenger-ref" href="{{url_for('main.logout')}}">Log out</a>
    </div>
{% endblock content %}

messenger/templates/register.html
{% extends "layout.html" %}
{% block content %}
<form method="POST" action="">
    {{ form.hidden_tag() }}
    <fieldset class="no-border">
      <div>
        {{ form.first_name.label }} 
        {% if form.first_name.errors %}
          {{form.first_name}}
          <div>
          {% for erorr in form.first_name.errors %}
            <span>{{erorr}}</span>
          {% endfor %}
          </div>
        {% else %}
          {{form.first_name }}
        {% endif %}
      </div>
      <div>
        {{ form.last_name.label }} 
        {% if form.last_name.errors %}
          {{form.last_name}}
          <div>
          {% for erorr in form.last_name.errors %}
            <span>{{erorr}}</span>
          {% endfor %}
          </div>
        {% else %}
          {{form.last_name }}
        {% endif %}
      </div>
      <div>
        {{ form.password.label }}
        {% if form.password.errors %}
          {{form.password}}
          <div>
          {% for erorr in form.password.errors %}
            <span>{{erorr}}</span>
          {% endfor %}
          </div>
        {% else %}
          {{form.password }} 
        {% endif %}
      </div>
      <div>
        {{ form.email.label }}
        {% if form.email.errors %}
          {{form.email}}
          <div>
          {% for erorr in form.email.errors %}
            <span>{{erorr}}</span>
          {% endfor %}
          </div>
        {% else %}
          {{form.email }} 
        {% endif %}
      </div>
    </fieldset>
    <div>{{ form.submit }}</div>
  </form>
  <a href="{{url_for('main.home')}}">Get me back to home page</a>
{% endblock content %}

messenger/templates/reply.html
{% extends "layout.html" %}
{% block content %}
<form method="POST" action="">
    {{ form.hidden_tag() }}
    <fieldset>
      <div>
        {{ form.content.label }} 
        {% if form.content.errors %}
          {{form.content}}
          <div>
          {% for erorr in form.content.errors %}
            <span>{{erorr}}</span>
          {% endfor %}
          </div>
        {% else %}
          {{form.content }}
        {% endif %}
      </div>
    </fieldset>
    <div>{{ form.submit }}</div>
  </form>
  <a href="{{url_for('main.messanger')}}">Get back to Messanger</a>
{% endblock content %}